config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount Flipflop::Engine => "/features"
  mount HealthMonitor::Engine, at: "/"

  resources :mediaflux_info, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticate :user, ->(user) { user.developer || user.sysadmin } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  get "/users-lookup", to: "users#lookup", as: :users_lookup
  resources :users, except: [:new, :destroy, :create] do
    get "/users/:user", action: :index, on: :collection
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "welcome#index"
  get "help", to: "welcome#help", as: :help
  get "dashboard", to: "dashboard#index"
  post "emulate", to: "dashboard#emulate", as: :emulate
  post "dash_project", to: "dashboard#dash_project", as: :dash_project
  post "dash_admin", to: "dashboard#dash_admin", as: :dash_admin

  resources :projects, except: [:new, :edit]
  get "projects/:id/details", to: "projects#details", as: :project_details
  get "projects/:id/list-contents", to: "projects#list_contents", as: :project_list_contents
  get "projects/:id/revision_confirmation", to: "projects#revision_confirmation", as: :project_revision_confirmation
  get "projects/file_list_download/:job_id", to: "projects#file_list_download", as: :project_file_list_download
  get "projects/:id/:id-mf", to: "projects#show_mediaflux", as: :project_show_mediaflux

  resources :requests do
    member do
      get :approve
    end
  end

  get "admin_edit_request/:id", to: "edit_requests#edit", as: :admin_edit_request
  put "admin_edit_request/:id", to: "edit_requests#update"

  namespace :api do
    namespace :v0 do
      resources :projects, only: [:index]
    end
  end

  mount ActionCable.server => "/cable"
  get "mediaflux_extra", to: "users/mediaflux_callbacks#cas", as: :mediaflux_extra
  get "mediaflux_passthru", to: "users/mediaflux_callbacks#passthru", as: :mediaflux_passthru

  put "project_import", to: "project_import#run"
  get "project_import", to: "dashboard#index"

  get "new-project/project-info/(:request_id)", to: "new_project_wizard/project_information#show", as: :new_project_project_info
  put "new-project/project-info/:request_id/save", to: "new_project_wizard/project_information#save", as: :new_project_project_info_save

  get "new-project/project-info-categories/:request_id", to: "new_project_wizard/project_information_categories#show", as: :new_project_project_info_categories
  put "new-project/project-info-categories/:request_id/save", to: "new_project_wizard/project_information_categories#save", as: :new_project_project_info_categories_save

  get "new-project/project-info-dates/:request_id", to: "new_project_wizard/project_information_dates#show", as: :new_project_project_info_dates
  put "new-project/project-info-dates/:request_id/save", to: "new_project_wizard/project_information_dates#save", as: :new_project_project_info_dates_save

  get "new-project/roles-people/:request_id", to: "new_project_wizard/roles_and_people#show", as: :new_project_roles_and_people
  put "new-project/roles-people/:request_id/save", to: "new_project_wizard/roles_and_people#save", as: :new_project_roles_and_people_save

  get "new-project/project-type/:request_id", to: "new_project_wizard/project_type#show", as: :new_project_project_type
  put "new-project/project-type/:request_id/save", to: "new_project_wizard/project_type#save", as: :new_project_project_type_save

  get "new-project/storage-access/:request_id", to: "new_project_wizard/storage_and_access#show", as: :new_project_storage_and_access
  put "new-project/storage-access/:request_id/save", to: "new_project_wizard/storage_and_access#save", as: :new_project_storage_and_access_save

  get "new-project/additional-info-grants-funding/:request_id", to: "new_project_wizard/additional_information_grants_and_funding#show",
                                                                as: :new_project_additional_information_grants_and_funding
  put "new-project/additional-info-grants-funding/:request_id/save", to: "new_project_wizard/additional_information_grants_and_funding#save",
                                                                     as: :new_project_additional_information_grants_and_funding_save

  get "new-project/additional-info-project-permissions/:request_id", to: "new_project_wizard/additional_information_project_permissions#show",
                                                                     as: :new_project_additional_information_project_permissions
  put "new-project/additional-info-project-permissions/:request_id/save", to: "new_project_wizard/additional_information_project_permissions#save",
                                                                          as: :new_project_additional_information_project_permissions_save

  get "new-project/additional-info-related-resources/:request_id", to: "new_project_wizard/additional_information_related_resources#show",
                                                                   as: :new_project_additional_information_related_resources
  put "new-project/additional-info-related-resources/:request_id/save", to: "new_project_wizard/additional_information_related_resources#save",
                                                                        as: :new_project_additional_information_related_resources_save

  get "new-project/review-submit/:request_id", to: "new_project_wizard/review_and_submit#show", as: :new_project_review_and_submit
  put "new-project/review-submit/:request_id/save", to: "new_project_wizard/review_and_submit#save", as: :new_project_review_and_submit_save

  get "request_submit", to: "request_submit#index"

  get "aql_queries", to: "aql_queries#index"

  # Catch any undefined path and render a 404 page not found
  get "*path", to: "application#render_not_found"
end
# rubocop:enable Metrics/BlockLength

app/controllers/dashboard_controller.rb
# frozen_string_literal: true
class DashboardController < ApplicationController
  layout "welcome"

  def index
    @presenter = DashboardPresenter.new(current_user: current_user)

    session[:dashtab] ||= "project" # default the session tab to projects
    @dash_session = session[:dashtab]
    @session_id = current_user.mediaflux_session
    @emulation_role = session[:emulation_role] || "Not Emulating"
  end

  def emulate
    return if Rails.env.production?

    absolute_user = User.find(current_user.id)
    return unless absolute_user.trainer?

    if params.key?("emulation_menu")
      session[:emulation_role] = params[:emulation_menu]
    end
  end

  def dash_project
    if params.key?("dashtab")
      session[:dashtab] = params[:dashtab]
    end
  end

  def dash_admin
    if params.key?("dashtab")
      session[:dashtab] = params[:dashtab]
    end
  end
end

app/views/dashboard/_admin_listing.html.erb
<div id="admin-listing">
   <% if current_user.eligible_sysadmin?%>
   <div class="section">
      <div class="import">
        <h2>Recently Approved Projects</h2> 
        <%= button_to "Import Mediaflux Projects", project_import_path, method: "put", class: "btn btn-dark btn-sm" %>
      </div>
      <% if !@presenter.all_projects.empty? %>
       <%= render partial: "projects_listing", locals: { projects: @presenter.all_projects,  table_id: "projects-listing-approved"} %>
      <% else %>
        <p> (none) </p>
      <% end %>
   </div>
   <%end%>
</div>

app/views/dashboard/_download_item.html.erb
<div class="download-item" >
  <div class="title">
    <%= user_request.download_link %>
  </div>
  <div class="details">
    <div class="expiration"><%= user_request.expiration %></div>
    <div class="size">
      <%= user_request.size %>
    </div>
  </div>
</div>

app/views/dashboard/_failed_item.html.erb
<div class="download-item" >
  <div class="title failed">
    <%= user_request.title %>
  </div>
  <div class="details">
    <div class="expiration">The download failed to complete</div>
    <div class="size">
      <%= link_to "retry", user_request.list_contents_url, target: "_blank" %>
    </div>
  </div>
</div>

app/views/dashboard/_new_project_request_wizard_link.html.erb
<div class="new-project-multi">
    <div class="request-btn">
        <%= link_to "New Project Request",
          new_project_project_info_path,
          class: "plausible-event-name=New+Project+Request",
          id: "new-project-request-wizard-button",
          tabindex: 0 %>
    </div>
    <div class="request-options">
        <button popovertarget="request-dropdown" class="down-arrow" aria-label="view draft and saved requests" title="view draft and saved requests"></button>
        <div popover="auto" id="request-dropdown" class="request-dropdown">
          <button class="request-button" popovertarget="draft-request-list">Saved Draft Requests</button>
          <button class="request-button" popovertarget="submitted-request-list">Submitted Requests</button>
        </div>

        <!-- draft requests popup -->
        <div popover="auto" id="draft-request-list" class=request-list pul-popover">
          <div class="modal-content">
            <div class="draft-list-header"> 
              <div class="model-title">Saved Draft Requests</div>
              <input type=button popovertarget="draft-request-list" popovertargetaction="hide" class="pul-popover-close" data="cancel"></input>
            </div>
            <div class="draft-content">
              <div class="draft-list">
                <% @presenter.my_draft_requests.each do | request_model| %>
                  <div class="draft-request">
                      <div class="request-name"><%= request_model.project_title.empty? ? "(no title entered)" : request_model.project_title %></div>
                      <div class="request-actions">
                        <a href="<%= new_project_review_and_submit_path(request_model.id)%>" class="request-open" focus="true" tabindex="0" aria-label="<%= request_model.project_title.empty? ? "(no title entered)" : request_model.project_title %> Open"><div>Open</div></a>
                        <!--div class="request-remove"><div class="request-remove-icon"></div><div>Delete</div></div-->
                      </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <!-- submitted requests popup -->
        <div popover="auto" id="submitted-request-list" class="request-list pul-popover">
          <div class="modal-content">
            <div class="draft-list-header"> 
              <div class="model-title">Submitted Requests</div>
              <input type=button popovertarget="submitted-request-list" popovertargetaction="hide" class="pul-popover-close" data="cancel"></input>
            </div>
            <div class="draft-content">
              <div class="draft-list">
                <% @presenter.my_submitted_requests.each do | request_model| %>
                  <div class="draft-request">
                      <div class="request-name"><%= request_model.project_title.empty? ? "(no title entered)" : request_model.project_title %></div>
                      <div class="request-actions">
                        <a href="<%= request_path(request_model.id)%>" class="request-open" focus="true" tabindex="0" aria-label="<%= request_model.project_title.empty? ? "(no title entered)" : request_model.project_title %> Open">
                          <div>Open</div>
                        </a>
                      </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

    </div>
</div>

app/views/dashboard/_project_list_view.html.erb
<tr class="project" >
    <td class="project-row">
        <div class="project-details">
            <div class="title">
                <a class="click-row" href="<%= project_path(project.id) %>" tabindex="0" ><%= project.title %></a>
            </div>
            <div class="summary">
                <div class="path"> <%= project.path %></div>
            </div>
            <div class="summary">
               <div class="status <%= project.status.downcase %>"><%= project.status %></div>
               <div class="type"><%= project.type %></div>
               <div class="role"><%= project.role(current_user) %></div>
               <div class="download"><%= project.latest_file_list_time %></div>
               <div class="activity"><%= project.last_activity %></div>
            </div>
        </div>
        <div class="storage-details">
          <div class="storage">
            <div class="w3-light-grey w3-round-xlarge">
                <div class="w3-orange w3-round-xlarge" style="height:6px;width:<%= project.quota_percentage(session_id: current_user.mediaflux_session, dashboard: true) %>%"></div>
            </div>
            <div class="usage"> <%= project.quota_usage(session_id: current_user.mediaflux_session) %></div>
          </div>
        </div>
    </td>
    <!-- table columns being kept, but not shown for DataTables sorting and search -->
    <td style="display: none"><%= project.title %></td>
    <td style="display: none"><%= project.status %></td>
    <td style="display: none"><%= project.type %></td>
    <td style="display: none"><%= project.role(current_user) %></td>
    <td style="display: none"><%= project.latest_file_list_time %></td>
    <td style="display: none"><%= project.last_activity %></td>
    <td style="display: none"><%= project.quota_usage(session_id: current_user.mediaflux_session) %></td>
</tr>

app/views/dashboard/_projects_listing.html.erb
<% if projects.count == 0 %>
  <%= render :partial => "startup_page" %>
<% else %>
  <div class="table">
    <table id="<%= table_id %>" width="100%" role="table"> <!-- width is needed to override datatables calculation -->
      <thead>
        <tr class="project heading screenreader-only" role="rowheader">
          <th>display</th>
          <th>title</th>
          <th>status</th>
          <th>type</td>
          <th>role</th>
          <th>download</th>
          <th>activity</th>
          <th>quota usage</th>
        </tr>
      </thead>
      <tbody>
        <%= render :partial => "project_list_view", :collection => projects, :as => :project %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/dashboard/_startup_page.html.erb
<div class="startup-content">
  <div class="startup-page">
    <h1>No Projects Yet</h1>
    <div class="startup-page-image">
      <%= image_tag("startup_image.svg", alt: "") %>
    </div>
    <div class="startup-prompt">
      <a href="<%= new_project_project_info_path %>">Start a new project</a> to see it listed here
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div id="welcome">
   <div class="main-content">
      <div class="welcome-pane">
         <h1>Welcome, <%= current_user.given_name %>!</h1>
         <%= render partial: "new_project_request_wizard_link" %>
      </div>

      <div class="dashboard-admin-buttons">
         <% if current_user.eligible_sysadmin? %>
         <%= link_to "Requests", requests_path(), class: "btn btn-dark btn-sm", id: "requests-listing-button" %>
         <% end %>
      </div>

      <div class="detail-pane">
         <div class="main">
            <div id="dashboard-nav">
               <button id="dash-projects" class="tab-nav"> Projects </button>
               <% if current_user.eligible_sysadmin? %>
               <button id="dash-admin" class="tab-nav"> Administration </button>
               <% elsif current_user.trainer? %>
               <% if session[:emulation_role] == "System Administrator" %>
               <button id="dash-admin" class="tab-nav"> Administration </button>
               <% end %>
               <% end %>
            </div>
            <% if @dash_session == "project"%>
              <%= render partial: "projects_listing", locals: { projects: @presenter.dashboard_projects,  table_id: "projects-listing" } %>
            <% elsif @dash_session == "admin" %>
              <%= render partial: "admin_listing" %>
            <% end %>
         </div>
         <div class="sidebar">
            <div class="downloads">
               <div class="header">
                  <div><i class="bi bi-download"></i> Latest Downloads</div>
               </div>
               <div class="contents-window">
                  <div class="details">
                     <div class="content">
                        <div class="container1">
                           <div class="container2">
                              <div class="container3">
                                 <% if current_user.latest_downloads.count == 0 %>
                                 <div class="download-item">No downloads available</div>
                                 <% else %>
                                   <% current_user.latest_downloads.each do |user_request| %>
                                     <%= render partial: user_request.partial_name, locals: { user_request: } %>
                                   <% end %>
                                 <% end %>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div class="contact-us">
               <div class="header">
                  <div>Don't see what your're looking for?</div>
               </div>
               <div class="contact-container">
                  <div class="contact-content">
                     <%= link_to "Contact us", "mailto:tigerdata@princeton.edu", class: "btn btn-sm" %>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<script type="module">
   // Make the AJAX call for version information explicitly on this page
   // (and for now only on this page) so that we don't make extra calls
   // to Mediaflux for every page loaded.
   dashStyle('<%= @dash_session %>');
   dashTab();
   displayMediafluxVersion('<%= mediaflux_info_index_path(format: "json") %>', <%= !current_user.nil? %>);

   // Setup the DataTables
   setupTable('#projects-listing');
   setupTable('#projects-listing-approved');
</script>