config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount Flipflop::Engine => "/features"
  mount HealthMonitor::Engine, at: "/"

  resources :mediaflux_info, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticate :user, ->(user) { user.developer || user.sysadmin } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  get "/users-lookup", to: "users#lookup", as: :users_lookup
  resources :users, except: [:new, :destroy, :create] do
    get "/users/:user", action: :index, on: :collection
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "welcome#index"
  get "help", to: "welcome#help", as: :help
  get "dashboard", to: "dashboard#index"
  post "emulate", to: "dashboard#emulate", as: :emulate
  post "dash_project", to: "dashboard#dash_project", as: :dash_project
  post "dash_admin", to: "dashboard#dash_admin", as: :dash_admin

  resources :projects, except: [:new, :edit]
  get "projects/:id/details", to: "projects#details", as: :project_details
  get "projects/:id/list-contents", to: "projects#list_contents", as: :project_list_contents
  get "projects/:id/revision_confirmation", to: "projects#revision_confirmation", as: :project_revision_confirmation
  get "projects/file_list_download/:job_id", to: "projects#file_list_download", as: :project_file_list_download
  get "projects/:id/:id-mf", to: "projects#show_mediaflux", as: :project_show_mediaflux

  resources :requests do
    member do
      get :approve
    end
  end

  get "admin_edit_request/:id", to: "edit_requests#edit", as: :admin_edit_request
  put "admin_edit_request/:id", to: "edit_requests#update"

  namespace :api do
    namespace :v0 do
      resources :projects, only: [:index]
    end
  end

  mount ActionCable.server => "/cable"
  get "mediaflux_extra", to: "users/mediaflux_callbacks#cas", as: :mediaflux_extra
  get "mediaflux_passthru", to: "users/mediaflux_callbacks#passthru", as: :mediaflux_passthru

  put "project_import", to: "project_import#run"
  get "project_import", to: "dashboard#index"

  get "new-project/project-info/(:request_id)", to: "new_project_wizard/project_information#show", as: :new_project_project_info
  put "new-project/project-info/:request_id/save", to: "new_project_wizard/project_information#save", as: :new_project_project_info_save

  get "new-project/project-info-categories/:request_id", to: "new_project_wizard/project_information_categories#show", as: :new_project_project_info_categories
  put "new-project/project-info-categories/:request_id/save", to: "new_project_wizard/project_information_categories#save", as: :new_project_project_info_categories_save

  get "new-project/project-info-dates/:request_id", to: "new_project_wizard/project_information_dates#show", as: :new_project_project_info_dates
  put "new-project/project-info-dates/:request_id/save", to: "new_project_wizard/project_information_dates#save", as: :new_project_project_info_dates_save

  get "new-project/roles-people/:request_id", to: "new_project_wizard/roles_and_people#show", as: :new_project_roles_and_people
  put "new-project/roles-people/:request_id/save", to: "new_project_wizard/roles_and_people#save", as: :new_project_roles_and_people_save

  get "new-project/project-type/:request_id", to: "new_project_wizard/project_type#show", as: :new_project_project_type
  put "new-project/project-type/:request_id/save", to: "new_project_wizard/project_type#save", as: :new_project_project_type_save

  get "new-project/storage-access/:request_id", to: "new_project_wizard/storage_and_access#show", as: :new_project_storage_and_access
  put "new-project/storage-access/:request_id/save", to: "new_project_wizard/storage_and_access#save", as: :new_project_storage_and_access_save

  get "new-project/additional-info-grants-funding/:request_id", to: "new_project_wizard/additional_information_grants_and_funding#show",
                                                                as: :new_project_additional_information_grants_and_funding
  put "new-project/additional-info-grants-funding/:request_id/save", to: "new_project_wizard/additional_information_grants_and_funding#save",
                                                                     as: :new_project_additional_information_grants_and_funding_save

  get "new-project/additional-info-project-permissions/:request_id", to: "new_project_wizard/additional_information_project_permissions#show",
                                                                     as: :new_project_additional_information_project_permissions
  put "new-project/additional-info-project-permissions/:request_id/save", to: "new_project_wizard/additional_information_project_permissions#save",
                                                                          as: :new_project_additional_information_project_permissions_save

  get "new-project/additional-info-related-resources/:request_id", to: "new_project_wizard/additional_information_related_resources#show",
                                                                   as: :new_project_additional_information_related_resources
  put "new-project/additional-info-related-resources/:request_id/save", to: "new_project_wizard/additional_information_related_resources#save",
                                                                        as: :new_project_additional_information_related_resources_save

  get "new-project/review-submit/:request_id", to: "new_project_wizard/review_and_submit#show", as: :new_project_review_and_submit
  put "new-project/review-submit/:request_id/save", to: "new_project_wizard/review_and_submit#save", as: :new_project_review_and_submit_save

  get "request_submit", to: "request_submit#index"

  get "aql_queries", to: "aql_queries#index"

  # Catch any undefined path and render a 404 page not found
  get "*path", to: "application#render_not_found"
end
# rubocop:enable Metrics/BlockLength

app/controllers/welcome_controller.rb
# frozen_string_literal: true
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :downtime_check
  skip_before_action :verify_authenticity_token

  def index
    if current_user.blank?
      render layout: "welcome"
    else
      redirect_to dashboard_path
    end
  end

  def help; end
end

app/views/welcome/_logged_in.html.erb
<div class="main-content">
    <div class="welcome-pane">
        <h1>Welcome, <%= current_user.given_name %>!</h1>
        <div class="project-button">
            <% if current_user.eligible_to_create_new? or (current_user.eligible_to_create_new? && @emulation_role == "Eligible Data Sponsor") %>
                <%= link_to "Create new project", new_project_path(), class: "btn btn-dark btn-sm" %>
            <% end %>
        </div>
    </div>
    <div class="detail-pane">
        <div class="main">
            <div id="dashboard-nav">
                <button id="dash-projects" class="tab-nav"> Projects </button>
                <% if current_user.eligible_sysadmin? %>
                    <button id="dash-admin" class="tab-nav"> Administration </button>
                <% elsif current_user.trainer? %>
                    <% if session[:emulation_role] == "System Administrator" %>
                        <button id="dash-admin" class="tab-nav"> Administration </button>
                    <% end %>
                <% end %>
            </div>
            <% if @dash_session == "project"%>
                <%= render partial: "projects_listing", locals: { projects: @dashboard_projects.sort_by(&:updated_at).reverse,  table_id: "projects-listing" } %>
            <% elsif @dash_session == "admin" %>
                <%= render partial: "admin_listing" %>
            <% end %>
        </div>
        <div class="sidebar">
            <div class="downloads">
                <div class="header">
                    <div><i class="bi bi-download"></i> Latest Downloads</div>
                </div>
                <div class="details">
                    <div class="content">
                        <div class="container1">
                        <div class="container2">
                        <div class="container3">
                            <% if current_user.latest_downloads.count == 0 %>
                                <div class="download-item">No downloads available</div>
                            <% else %>
                                <%= render partial: "download_item", collection: current_user.latest_downloads, as: "download" %>
                            <% end %>
                        </div>
                        </div>
                        </div>
                    </div>
                    <div class="scrollbar">
                        <div class="indicator">&nbsp;</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/welcome/_login_disabled.html.erb
<div class="alert alert-danger">
  <h2>TigerData is temporarily unavailable</h2>
  We apologize for the disruption. Please bear with us as our teams work to return our systems to regular service as soon as possible. Look for updates from the TIGERDATA-USERS listserv, or contact us at tigerdata@princeton.edu if you have urgent concerns.
</div>

app/views/welcome/help.html.erb
<p>TigerData is still under construction, and you are not registered as a tester at this time.</p>

<p>If you have any questions, please contact the team at <%= link_to("tigerdata@princeton.edu", "mailto:tigerdata@princeton.edu") %>.</p>

app/views/welcome/index.html.erb
<div id="welcome">
  <div class="welcome-portal">
      <div class="welcome-left">
        <div class="welcome-text">
          <div class="welcome-heading">
              <%= render partial: "login_disabled" if Flipflop.disable_login? %>
              <h3>Welcome to</h3>
              <h1>TigerData Web Portal</h1>
          </div>
          <div class="welcome-body"> 
            <p>TigerData is a data management service for the Princeton research community that includes a suite of software tools and scalable, tiered storage to enable the organization, description, storage, sharing, and long-term sustainability of research and administrative data. </p>
            <p>It enables the things you want to do (with your data), and makes it easier to do the things you have to do.</p>
          </div>
          <%= button_to "Learn More", "https://tigerdata.princeton.edu", class: "pul-button pul-button-primary", id: "learn-more-button" %>

          <div class="welcome-warn">
              <p>Log in is currently limited to early adopters. <%= link_to "Contact us", "mailto:td-frontend@princeton.edu" %> for more information.</p>
          </div>
        </div>
      </div>
      <div class="welcome-right">
          <div class="welcome-image"></div> <!-- image displayed in welcome_portal.scss -->
      </div>
  </div>
</div>