config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount Flipflop::Engine => "/features"
  mount HealthMonitor::Engine, at: "/"

  resources :mediaflux_info, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticate :user, ->(user) { user.developer || user.sysadmin } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  get "/users-lookup", to: "users#lookup", as: :users_lookup
  resources :users, except: [:new, :destroy, :create] do
    get "/users/:user", action: :index, on: :collection
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "welcome#index"
  get "help", to: "welcome#help", as: :help
  get "dashboard", to: "dashboard#index"
  post "emulate", to: "dashboard#emulate", as: :emulate
  post "dash_project", to: "dashboard#dash_project", as: :dash_project
  post "dash_admin", to: "dashboard#dash_admin", as: :dash_admin

  resources :projects, except: [:new, :edit]
  get "projects/:id/details", to: "projects#details", as: :project_details
  get "projects/:id/list-contents", to: "projects#list_contents", as: :project_list_contents
  get "projects/:id/revision_confirmation", to: "projects#revision_confirmation", as: :project_revision_confirmation
  get "projects/file_list_download/:job_id", to: "projects#file_list_download", as: :project_file_list_download
  get "projects/:id/:id-mf", to: "projects#show_mediaflux", as: :project_show_mediaflux

  resources :requests do
    member do
      get :approve
    end
  end

  get "admin_edit_request/:id", to: "edit_requests#edit", as: :admin_edit_request
  put "admin_edit_request/:id", to: "edit_requests#update"

  namespace :api do
    namespace :v0 do
      resources :projects, only: [:index]
    end
  end

  mount ActionCable.server => "/cable"
  get "mediaflux_extra", to: "users/mediaflux_callbacks#cas", as: :mediaflux_extra
  get "mediaflux_passthru", to: "users/mediaflux_callbacks#passthru", as: :mediaflux_passthru

  put "project_import", to: "project_import#run"
  get "project_import", to: "dashboard#index"

  get "new-project/project-info/(:request_id)", to: "new_project_wizard/project_information#show", as: :new_project_project_info
  put "new-project/project-info/:request_id/save", to: "new_project_wizard/project_information#save", as: :new_project_project_info_save

  get "new-project/project-info-categories/:request_id", to: "new_project_wizard/project_information_categories#show", as: :new_project_project_info_categories
  put "new-project/project-info-categories/:request_id/save", to: "new_project_wizard/project_information_categories#save", as: :new_project_project_info_categories_save

  get "new-project/project-info-dates/:request_id", to: "new_project_wizard/project_information_dates#show", as: :new_project_project_info_dates
  put "new-project/project-info-dates/:request_id/save", to: "new_project_wizard/project_information_dates#save", as: :new_project_project_info_dates_save

  get "new-project/roles-people/:request_id", to: "new_project_wizard/roles_and_people#show", as: :new_project_roles_and_people
  put "new-project/roles-people/:request_id/save", to: "new_project_wizard/roles_and_people#save", as: :new_project_roles_and_people_save

  get "new-project/project-type/:request_id", to: "new_project_wizard/project_type#show", as: :new_project_project_type
  put "new-project/project-type/:request_id/save", to: "new_project_wizard/project_type#save", as: :new_project_project_type_save

  get "new-project/storage-access/:request_id", to: "new_project_wizard/storage_and_access#show", as: :new_project_storage_and_access
  put "new-project/storage-access/:request_id/save", to: "new_project_wizard/storage_and_access#save", as: :new_project_storage_and_access_save

  get "new-project/additional-info-grants-funding/:request_id", to: "new_project_wizard/additional_information_grants_and_funding#show",
                                                                as: :new_project_additional_information_grants_and_funding
  put "new-project/additional-info-grants-funding/:request_id/save", to: "new_project_wizard/additional_information_grants_and_funding#save",
                                                                     as: :new_project_additional_information_grants_and_funding_save

  get "new-project/additional-info-project-permissions/:request_id", to: "new_project_wizard/additional_information_project_permissions#show",
                                                                     as: :new_project_additional_information_project_permissions
  put "new-project/additional-info-project-permissions/:request_id/save", to: "new_project_wizard/additional_information_project_permissions#save",
                                                                          as: :new_project_additional_information_project_permissions_save

  get "new-project/additional-info-related-resources/:request_id", to: "new_project_wizard/additional_information_related_resources#show",
                                                                   as: :new_project_additional_information_related_resources
  put "new-project/additional-info-related-resources/:request_id/save", to: "new_project_wizard/additional_information_related_resources#save",
                                                                        as: :new_project_additional_information_related_resources_save

  get "new-project/review-submit/:request_id", to: "new_project_wizard/review_and_submit#show", as: :new_project_review_and_submit
  put "new-project/review-submit/:request_id/save", to: "new_project_wizard/review_and_submit#save", as: :new_project_review_and_submit_save

  get "request_submit", to: "request_submit#index"

  get "aql_queries", to: "aql_queries#index"

  # Catch any undefined path and render a 404 page not found
  get "*path", to: "application#render_not_found"
end
# rubocop:enable Metrics/BlockLength

app/models/mediaflux/request.rb
# frozen_string_literal: true
module Mediaflux
    class Request

      # As this is an abstract class, this should be overridden to specify the Mediaflux API service
      def self.service
        raise(NotImplementedError, "#{self} is an abstract class, please override #{self}.service")
      end

      # The default request URL path for the Mediaflux API
      # @return [String]
      def self.request_path
        "/__mflux_svc__"
      end

      def self.uri
        # Setting the URI to the Ansible build or Docker build of mediaflux depending on the environment
        URI("#{Connection.transport}://#{Connection.host}:#{Connection.port}#{request_path}")
      end

      # Constructs a new HTTP POST request for usage with the Mediaflux API
      # @return [Net::HTTP::Post]
      def self.build_post_request
        Net::HTTP::Post.new(request_path)
      end

      # The default XML namespace which should be used for building the XML
      #   Document transmitted in the body of the HTTP request
      # @return [String]
      def self.default_xml_namespace
        "tigerdata"
      end

      def self.default_xml_namespace_uri
        "http://tigerdata.princeton.edu"
      end

      # Constructs and memoizes a new instance of the Net::HTTP::Persistent object at the level of the Class
      # @returns http_client [Net::HTTP::Persistent] HTTP client for transmitting requests to the Mediaflux server API
      def self.find_or_create_http_client
        HttpConnection.instance.http_client
      end

      attr_reader :session_token

      # Constructor
      # @param file [File] any upload file required for the POST request
      # @param session_token [String] the API token for the authenticated session
      # @param http_client [Net::HTTP::Persistent] HTTP client for transmitting requests to the Mediaflux server API
      def initialize(file: nil, session_token: nil, http_client: nil)
        @http_client = http_client || self.class.find_or_create_http_client
        @file = file
        @session_token = session_token
      end

      # Resolves the HTTP request against the Mediaflux API
      # @return [Net::HTTP]
      def resolve
        start_time = ::Time.zone.now
        @http_response = @http_client.request self.class.uri, http_request
        log_elapsed(start_time)
        @http_response
      end

      # Determines whether or not the request has been resolved
      # @return [Boolean]
      def resolved?
        @http_response.present?
      end

      # Resolves the HTTP request, and returns the XML Document parsed from the response body
      # @return [Nokogiri::XML::Document]
      def response_xml
        resolve unless resolved?
        Rails.logger.debug(response_body)
        @response_xml ||= Nokogiri::XML.parse(response_body)
        Rails.logger.debug(@response_xml)
        if @response_xml.xpath("//message").text == "session is not valid"
          raise Mediaflux::SessionExpired, "Session expired for token #{session_token}"
        end

        @response_xml
      end

      # The response body of the mediaflux call
      def response_body
        @response_body ||= http_response.body
      end

      def error?
        response_error.present?
      end

      def response_error
        xml = response_xml
        return nil if xml.xpath("/response/reply/error").count == 0
        error = {
          title: xml.xpath("/response/reply/error").text,
          message: xml.xpath("/response/reply/message").text
        }
        Rails.logger.error "MediaFlux error: #{error[:title]}, #{error[:message]}"
        error
      end

      delegate :to_s, to: :response_xml

      def xml_payload( name: self.class.service)
        body = build_http_request_body(name: )
        xml_payload = body.to_xml
      end

      # The output of this routine can be passed to xtoshell in aterm.  The output of which can be sent to service.execute
      # @param [String] name name of the service this request will send
      # @return [String] xml that can be passed to xtoshell without manipulation
      def xtoshell_xml( name: self.class.service)
        xml_builder = build_http_request_body(name: )
        xml_builder.doc.xpath("//request/service/@session").remove
        xml = xml_builder.to_xml(:save_with => Nokogiri::XML::Node::SaveOptions::AS_XML | Nokogiri::XML::Node::SaveOptions::NO_DECLARATION)
        xml.strip.gsub("\"","'").gsub("<args>","").gsub("</args>","")
      end

      # This method is used for transforming iso8601 dates to dates that MediaFlux likes
      # Take a string like "2024-02-26T10:33:11-05:00" and convert this string to "22-FEB-2024 13:57:19"
      def self.format_date_for_mediaflux(iso8601_date)
        return if iso8601_date.nil?
        Time.format_date_for_mediaflux(iso8601_date)
      end

      private

        def http_request
          @http_request ||= build_http_request(name: self.class.service, form_file: @file)
        end

        def http_response
          @http_response ||= resolve
        end

        def build_http_request_body(name:)
          args = { name: name }
                                                # must use @session_token here instead of session_token
                                                #  for login to not go into an infinaite loop
          args[:session] = session_token unless @session_token.nil?

          Nokogiri::XML::Builder.new(namespace_inheritance: false) do |xml|
            xml.request do
              xml.service(**args) do
                yield xml if block_given?
              end
            end
          end
        end

        # rubocop:disable Metrics/MethodLength
        def build_http_request(name:, form_file: nil)
          request = self.class.build_post_request

          log_xml_request(xml_payload)
          if form_file.nil?
            request["Content-Type"] = "text/xml; charset=utf-8"
            request.body = xml_payload(name:)
          else
            request["Content-Type"] = "multipart/form-data"
            request.set_form({ "request" => xml_payload,
                               "nb-data-attachments" => "1",
                               "file_0" => form_file },
                          "multipart/form-data",
                          "charset" => "UTF-8")
          end

          request
        end
      # rubocop:enable Metrics/MethodLength

      def log_xml_request(xml_payload)
        password_element = xml_payload.match(/\<password\>.*\<\/password\>/)
        if password_element.nil?
          Rails.logger.debug(xml_payload)
        else
          # Don't log the password
          Rails.logger.debug(xml_payload.gsub(password_element.to_s, "<password>***</password>"))
        end
      end

      # Logs as warning Mediaflux requests that take longer than 3 seconds.
      #
      # We could eventually also send to Honeybadger long requests but
      # let's wait until we have a benchmark of what is considered slow
      # in Mediaflux.
      def log_elapsed(start_time)
        elapsed_time = ::Time.zone.now - start_time
        timing_info = "#{format('%.2f', elapsed_time)} s"
        if elapsed_time > 3.0
          Rails.logger.warn "Slow Mediaflux request: #{self.class}, #{timing_info}"
        end
      end
    end
end

app/controllers/requests_controller.rb
# frozen_string_literal: true
class RequestsController < ApplicationController
  before_action :set_breadcrumbs

  # GET /requests
  def index
    if current_user.eligible_sysadmin?
      add_breadcrumb("Project Requests - All")
      @draft_requests = Request.where(state: Request::DRAFT).map do |request|
        request.project_title = "no title set" if request.project_title.blank?
        request
      end
      @submitted_requests = Request.where(state: Request::SUBMITTED)
    else
      error_message = "You do not have access to this page."
      flash[:notice] = error_message
      redirect_to dashboard_path
    end
  end

  def show
    if current_user.developer || current_user.sysadmin || current_user.trainer
      @request_model = Request.find(params[:id])
      @request_presenter = RequestPresenter.new(@request_model)
      add_breadcrumb("New Project Request", new_project_project_info_path)
      render :show
    else
      error_message = "You do not have access to this page."
      flash[:notice] = error_message
      redirect_to dashboard_path
    end
  end

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength
  # rubocop:disable Metrics/PerceivedComplexity
  # rubocop:disable Metrics/CyclomaticComplexity
  def approve
    if eligible_to_approve
      @request_model = Request.find(params[:id])
      if @request_model.valid_to_submit?
        project = @request_model.approve(current_user)
        @request_model.destroy!
        stub_message = "The request has been approved and this project was created in the TigerData web portal.  The request has been processed and deleted."
        TigerdataMailer.with(project_id: project.id, approver: current_user).project_creation.deliver_later
        redirect_to project_path(project.id), notice: stub_message
      else
        redirect_to new_project_review_and_submit_path(@request_model)
      end
    else
      error_message = "You do not have access to this page."
      flash[:notice] = error_message
      redirect_to dashboard_path
    end
  rescue StandardError => ex
    if ex.is_a?(Mediaflux::SessionExpired) || ex.cause.is_a?(Mediaflux::SessionExpired)
      raise
    elsif ex.is_a?(ProjectCreate::ProjectCreateError) && ex.message.include?("Session expired for token")
      raise Mediaflux::SessionExpired
    else
      Rails.logger.error "Error approving request #{params[:id]}. Details: #{ex.message}"
      Honeybadger.notify "Error approving request #{params[:id]}. Details: #{ex.message}"
      flash[:notice] = "Error approving request #{params[:id]}"
      redirect_to request_path(@request_model)
    end
  end
  # rubocop:enable Metrics/MethodLength
  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/PerceivedComplexity
  # rubocop:enable Metrics/CyclomaticComplexity

  private

    def set_breadcrumbs
      add_breadcrumb("Dashboard", dashboard_path)
    end

    def eligible_to_approve
      current_user.sysadmin || (current_user.developer && !Rails.env.production?)
    end
end

app/views/requests/_request_list.html.erb
<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>Requestor</th>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
    <% request_list.each do |request| %> 
        <tr>
        <td><%=request.project_path %> </td>
        <td><%=request.requestor %> </td>
        <td><%= link_to request.project_title, request_path(request.id) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/index.html.erb
<h1>New Project Requests</h1>
<h2>Submitted Requests</h2>
<%= render partial: "request_list", locals: {request_list: @submitted_requests } %>
<h2>Draft Requests</h2>
<%= render partial: "request_list", locals: {request_list: @draft_requests } %>

app/views/requests/show.html.erb
<div class="heading-frame">
  <% if @request_model.error_message.present? %>
  <p class="error-field">There was an error with this request</p>
  <textarea class="disabled-field" rows="10" cols="50">
      <%= @request_model.error_message %>
    </textarea>
  <% end %>

  <div class="black-circle">
    <div class="floppy-disk">
    </div>
  </div>

  <div class="request-heading">Your new project request has been saved</div>
  <div class="request-subheading">Your project has been saved and may be edited</div>
  <div class="return-dashboard">
    <%= link_to "Return to Dashboard", dashboard_path, class: "btn btn-dark" %>
    <div class="horizontal-frame">
      <% if @request_presenter.eligible_to_edit?(current_user)%>
        <% if @request_model.submitted?%>
          <%= link_to "Edit submitted request", admin_edit_request_path(@request_model.id),class: "btn btn-dark" %>
          <%= link_to "Approve request", approve_request_path(@request_model.id), class: "btn btn-dark" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1" viewBox="0 0 1200 1" fill="none">
    <path d="M6.36558e-08 0.5L1200 0.500105" stroke="#EEEEEE"/>
  </svg>

  <div class="saved-summary">Saved Summary</div>
    <% if @request_presenter.eligible_to_edit?(current_user)%>
      <% if !@request_model.submitted?%>
        <div class="blue-box">
          <div class="box-heading">
              <div class="pul-container">
                <div class="pul-info"> </div>
                <div class="pul-info-text">This new project request has not been submitted.</div>
              </div>
              <div class="box-subheading">
                <div class="pul-info-subheading">Continue editing your request to submit it.</div>
              </div>
          </div>
          <div class="continue-edit">
            <%= link_to "Continue Editing", new_project_project_info_path(@request_model.id),class: "btn btn-dark btn-sm" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <ul class="request-fields">
    <div class="detail-heading">
      <div class="heading-text">Basic Info </div>
      <% if @request_presenter.eligible_to_edit?(current_user)%>
        <% if !@request_model.submitted?%>
          <%= link_to "Edit", new_project_project_info_path(@request_model.id), class: "edit-link basic-info"%>
        <% end %>
      <% end %>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Project Title</li>
      <p class="detail-value"><%= @request_model.project_title %></p>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Project Directory</li>
      <p class="detail-value"><%= @request_presenter.project_directory %></p>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Project Purpose</li>
      <p class="detail-value"><%= @request_model.project_purpose %></p>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Project Description</li>
      <p class="detail-value"><%=@request_model.description %></p>
    </div>
    <div class="detail-pair">
        <li class="detail-subheading">Department(s)</li>
        <p class="detail-value"><%=@request_presenter.departments_list %></p>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1" viewBox="0 0 1200 1" fill="none">
      <path d="M6.36558e-08 0.5L1200 0.500105" stroke="#EEEEEE"/>
    </svg>

    <div class="detail-heading">
      <div class="heading-text">Roles and People(s) </div>
      <% if @request_presenter.eligible_to_edit?(current_user)%>
        <% if !@request_model.submitted?%>
         <%= link_to "Edit", new_project_roles_and_people_path(@request_model.id), class: "edit-link roles-people"%>
        <% end %>
      <% end %>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Data Sponsor</li>
      <p class="detail-value"> <%= @request_presenter.data_sponsor %></p>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Data Manager</li>
      <p class="detail-value"><%= @request_presenter.data_manager %></p>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Data User(s)</li>
      <p class="detail-value"><%=@request_presenter.user_list %></p>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1" viewBox="0 0 1200 1" fill="none">
      <path d="M6.36558e-08 0.5L1200 0.500105" stroke="#EEEEEE"/>
    </svg>

    <div class="detail-heading">
      <div class="heading-text">Storage and Access </div>
      <% if @request_presenter.eligible_to_edit?(current_user)%>
        <% if !@request_model.submitted?%>
          <%= link_to "Edit", new_project_storage_and_access_path(@request_model.id), class: "edit-link storage-access"%>
        <% end %>
      <% end %>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Storage Needed</li>
      <p class="detail-value"><%= @request_model.approved_quota_size %> <%= @request_model.approved_quota_unit %></p>
    </div>
    <div class="detail-pair">
      <li class="detail-subheading">Estimated Number of Files</li>
      <p class="detail-value"><%= @request_model.number_of_files %></p>
    </div>

    <div class="detail-heading">Connection Options</div>
    <div class="detail-pair">
      <li class="storage-heading">Do you need to connect to HPC?</li>
      <p class="detail-value"><%= @request_model.hpc %></p>
    </div>
    <div class="detail-pair">
      <li class="storage-heading">Do you need SMB (network file share)?</li>
      <p class="detail-value"><%= @request_model.smb %></p>
    </div>
    <div class="detail-pair">
      <li class="storage-heading">Do you need to enable Globus transfers?</li>
      <p class="detail-value"> <%= @request_model.globus %></p>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1" viewBox="0 0 1200 1" fill="none">
      <path d="M6.36558e-08 0.5L1200 0.500105" stroke="#EEEEEE"/>
    </svg>
  </ul>
</div>