config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount Flipflop::Engine => "/features"
  mount HealthMonitor::Engine, at: "/"

  resources :mediaflux_info, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticate :user, ->(user) { user.developer || user.sysadmin } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  get "/users-lookup", to: "users#lookup", as: :users_lookup
  resources :users, except: [:new, :destroy, :create] do
    get "/users/:user", action: :index, on: :collection
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "welcome#index"
  get "help", to: "welcome#help", as: :help
  get "dashboard", to: "dashboard#index"
  post "emulate", to: "dashboard#emulate", as: :emulate
  post "dash_project", to: "dashboard#dash_project", as: :dash_project
  post "dash_admin", to: "dashboard#dash_admin", as: :dash_admin

  resources :projects, except: [:new, :edit]
  get "projects/:id/details", to: "projects#details", as: :project_details
  get "projects/:id/list-contents", to: "projects#list_contents", as: :project_list_contents
  get "projects/:id/revision_confirmation", to: "projects#revision_confirmation", as: :project_revision_confirmation
  get "projects/file_list_download/:job_id", to: "projects#file_list_download", as: :project_file_list_download
  get "projects/:id/:id-mf", to: "projects#show_mediaflux", as: :project_show_mediaflux

  resources :requests do
    member do
      get :approve
    end
  end

  get "admin_edit_request/:id", to: "edit_requests#edit", as: :admin_edit_request
  put "admin_edit_request/:id", to: "edit_requests#update"

  namespace :api do
    namespace :v0 do
      resources :projects, only: [:index]
    end
  end

  mount ActionCable.server => "/cable"
  get "mediaflux_extra", to: "users/mediaflux_callbacks#cas", as: :mediaflux_extra
  get "mediaflux_passthru", to: "users/mediaflux_callbacks#passthru", as: :mediaflux_passthru

  put "project_import", to: "project_import#run"
  get "project_import", to: "dashboard#index"

  get "new-project/project-info/(:request_id)", to: "new_project_wizard/project_information#show", as: :new_project_project_info
  put "new-project/project-info/:request_id/save", to: "new_project_wizard/project_information#save", as: :new_project_project_info_save

  get "new-project/project-info-categories/:request_id", to: "new_project_wizard/project_information_categories#show", as: :new_project_project_info_categories
  put "new-project/project-info-categories/:request_id/save", to: "new_project_wizard/project_information_categories#save", as: :new_project_project_info_categories_save

  get "new-project/project-info-dates/:request_id", to: "new_project_wizard/project_information_dates#show", as: :new_project_project_info_dates
  put "new-project/project-info-dates/:request_id/save", to: "new_project_wizard/project_information_dates#save", as: :new_project_project_info_dates_save

  get "new-project/roles-people/:request_id", to: "new_project_wizard/roles_and_people#show", as: :new_project_roles_and_people
  put "new-project/roles-people/:request_id/save", to: "new_project_wizard/roles_and_people#save", as: :new_project_roles_and_people_save

  get "new-project/project-type/:request_id", to: "new_project_wizard/project_type#show", as: :new_project_project_type
  put "new-project/project-type/:request_id/save", to: "new_project_wizard/project_type#save", as: :new_project_project_type_save

  get "new-project/storage-access/:request_id", to: "new_project_wizard/storage_and_access#show", as: :new_project_storage_and_access
  put "new-project/storage-access/:request_id/save", to: "new_project_wizard/storage_and_access#save", as: :new_project_storage_and_access_save

  get "new-project/additional-info-grants-funding/:request_id", to: "new_project_wizard/additional_information_grants_and_funding#show",
                                                                as: :new_project_additional_information_grants_and_funding
  put "new-project/additional-info-grants-funding/:request_id/save", to: "new_project_wizard/additional_information_grants_and_funding#save",
                                                                     as: :new_project_additional_information_grants_and_funding_save

  get "new-project/additional-info-project-permissions/:request_id", to: "new_project_wizard/additional_information_project_permissions#show",
                                                                     as: :new_project_additional_information_project_permissions
  put "new-project/additional-info-project-permissions/:request_id/save", to: "new_project_wizard/additional_information_project_permissions#save",
                                                                          as: :new_project_additional_information_project_permissions_save

  get "new-project/additional-info-related-resources/:request_id", to: "new_project_wizard/additional_information_related_resources#show",
                                                                   as: :new_project_additional_information_related_resources
  put "new-project/additional-info-related-resources/:request_id/save", to: "new_project_wizard/additional_information_related_resources#save",
                                                                        as: :new_project_additional_information_related_resources_save

  get "new-project/review-submit/:request_id", to: "new_project_wizard/review_and_submit#show", as: :new_project_review_and_submit
  put "new-project/review-submit/:request_id/save", to: "new_project_wizard/review_and_submit#save", as: :new_project_review_and_submit_save

  get "request_submit", to: "request_submit#index"

  get "aql_queries", to: "aql_queries#index"

  # Catch any undefined path and render a 404 page not found
  get "*path", to: "application#render_not_found"
end
# rubocop:enable Metrics/BlockLength

app/controllers/projects_controller.rb
# frozen_string_literal: true
class ProjectsController < ApplicationController

  before_action :set_breadcrumbs
  before_action :authenticate_user!

  def details
    return if project.blank?

    add_breadcrumb(@presenter.title, project_path)
    add_breadcrumb("Details")

    @provenance_events = project.provenance_events.where.not(event_type: ProvenanceEvent::STATUS_UPDATE_EVENT_TYPE)

    @project_eligible_to_edit = true if project.status == Project::APPROVED_STATUS && eligible_editor?

    @project_metadata = @project.metadata
    @storage_capacity = @project_metadata[:storage_capacity]
    @size = @storage_capacity[:size]
    @unit = @storage_capacity[:unit]

    @requested_size = @size[:requested]
    @requested_unit = @unit[:requested]

    @approved_size = @size[:approved]
    @approved_unit = @unit[:approved]

    @storage_expectations = @project_metadata[:storage_performance_expectations]
    @requested_storage_expectations = @storage_expectations[:requested]
    @approved_storage_expectations = @storage_expectations[:approved]

    @project_session = "details"

    respond_to do |format|
      format.html do
        render
      end
      format.json do
        render json: project.to_json
      end
      format.xml do
        render xml: @presenter.to_xml
      end
    end
  end

  def index
    if current_user.eligible_sysadmin?
      search_projects
    else
      flash[:alert] = I18n.t(:access_denied)
      redirect_to dashboard_path
    end
  end

  def show
    return if project.blank?

    add_breadcrumb(@presenter.title, project_path)
    add_breadcrumb("Contents")

    @latest_completed_download = current_user.user_requests.where(project_id: @project.id, state: "completed").order(:completion_time).last
    @storage_usage = project.storage_usage(session_id: current_user.mediaflux_session)
    @storage_capacity = project.storage_capacity(session_id: current_user.mediaflux_session)

    @num_files = project.asset_count(session_id: current_user.mediaflux_session)

    @file_list = project.file_list(session_id: current_user.mediaflux_session, size: 100)
    @files = @file_list[:files]
    @files.sort_by!(&:path)

    @project_session = "content"
    respond_to do |format|
      format.html { render }
      format.xml { render xml: ProjectShowPresenter.new(project, current_user).to_xml
    }
    end
  end

  # GET "projects/:id/:id-mf"
  #
  # This action is used to render the mediaflux metadata for a project.
  def show_mediaflux
    project_id = params[:id]
    project = Project.find(project_id)
    respond_to do |format|
      format.xml do
        render xml: project.mediaflux_meta_xml(user: current_user)
      end
    end
  rescue => ex
    Rails.logger.error "Error getting MediaFlux XML for project #{project_id}, user #{current_user.uid}: #{ex.message}"
    flash[:alert] = "Error fetching Mediaflux XML for this project"
    redirect_to project_path(project_id)
  end

  def list_contents
    return if project.blank?

    project_job_service.list_contents_job(user: current_user)

    json_response = {
      message: "File list for \"#{project.title}\" is being generated in the background. A link to the downloadable file list will be available in the \"Recent Activity\" section of your dashboard when it is available. You may safely navigate away from this page or close this tab."
    }
    render json: json_response
  rescue => ex
    message = "Error producing document list (project id: #{project&.id}): #{ex.message}"
    Rails.logger.error(message)
    Honeybadger.notify(message)
    render json: { message: "Document list could not be generated." }
  end

  def file_list_download
    job_id = params[:job_id]
    user_request = FileInventoryRequest.where(job_id:job_id).first
    if user_request.nil?
      # TODO: handle error
      redirect_to "/"
    else
      filename = user_request.output_file
      send_data File.read(filename), type: "text/plain", filename: "filelist.csv", disposition: "attachment"
    end
  end

  private

    def project_job_service
      @project_job_service ||= ProjectJobService.new(project:)
    end


    def build_new_project
      @project ||= Project.new
    end

    def project
      @project ||= begin
        project = Project.find(params[:id])
        @presenter = ProjectShowPresenter.new(project, current_user)
        if project&.mediaflux_id != nil && @presenter.user_has_access?(user: current_user)
          project
        else
          flash[:alert] = I18n.t(:access_denied)
          redirect_to dashboard_path
          nil
        end
      end
    end

    def eligible_editor?
      return true if current_user.eligible_sponsor? or current_user.eligible_manager?
    end

    def set_breadcrumbs
      add_breadcrumb("Dashboard",dashboard_path)
    end

    def search_projects
      @title_query = if params[:title_query].present?
        params[:title_query]
      else
        "*" # default to all projects
      end
      result =  ProjectSearch.new.call(search_string: @title_query, requestor: current_user)
      if result.success?
        flash[:notice] = "Successful search in Mediaflux for #{@title_query}"
        # As of today the search results and the Dashboard show similar information (a list of projects)
        # and it makes sense to use the same presenter. If once we flesh out the search feature the
        # results become too different from each other we can create a specific presenter for the search
        # results.
        @project_presenters = result.value!.map { |project| ProjectDashboardPresenter.new(project, current_user) }
      else
        flash[:notice] = "Error searching projects for #{@title_query}.  Error: #{result.failure}"
        @project_presenters = []
      end
    end
end

app/views/projects/_confirmation.html.erb
  <div class="pending-project">
  <h2> New Project Request Received </h2>

    <p>Thank you for your submission.</p>

    <p>Your request is in the queue. Please allow 5 business days for our team to review your needs and set everything up.</p>

    <p>You can check up on your project status and make revisions at any time from your TigerData dashboard. 
    
    If you have questions, please contact the team at <%= mail_to "tigerdata@princeton.edu" %>.</p>

  <%= button_to "Return to Dashboard", root_path, class: "btn btn-primary btn-sm", method: :get %>

  </div>

app/views/projects/_content_view.html.erb
<tr class="content">
    <td><%= file.name %></td>
    <td><%= file.path_only %></td>
    <td><%=  number_to_human_size(file.size)%></td>
    <td><%= file.last_modified %></td>
</tr>

app/views/projects/_contents.html.erb
<div class="content-info"><i class="bi bi-info-circle"></i>Showing the first 100 files due to preview limit.</div>
<div class="table project-files">
   <table id="project-contents" >
   <thead>
      <tr class="content heading">
         <th class="sorting">name</th>
         <th>relative path</th>
         <th>size</th>
         <th>last updated</th>
      </tr>
   </thead>
   <tbody>
      <%= render :partial => "content_view", :collection => @files, :as => :file %>
   </tbody>
   </table>
</div>

app/views/projects/_latest_download_link.html.erb
<% if @latest_completed_download.completion_time %>
  <%= link_to("Download latest report - generated #{time_ago_in_words(@latest_completed_download.completion_time)} ago", project_file_list_download_path(job_id: @latest_completed_download.job_id, target: "_blank")) %>
<% end %>

app/views/projects/_project_details_heading.html.erb
<div id="project-details-heading">

  <div class="row">
    <div class="col-6 col-md-8">
      <h1><%= @presenter.title %></h1>
    <div class="heading-decoration"></div>
    </div>
    <div class="col-6 col-md-4">
      <div class="status <%= @presenter.status.downcase %>">
        <%= @presenter.status %>
      </div>
    </div>
  </div><!-- .row -->

  <div class="row">
    <div class="col-lg-6"><!-- .col -->

      <div id="project-description">
        <div id="description-text" class="truncate">
          <%= @presenter.description %>
        </div>
        <a id="show-more-less-link" class="show-more" href="#"><span>more</span></a>
      </div><!-- #project-description -->

      <div class="row">
        <div class="col-12">
          <div class="date-and-data-info">
            <ul>
              <li><span class="label">Date Created:</span> <%= @presenter.created %></li>
              <li><span class="label">Last updated:</span> <%= @presenter.updated %></li>
            </ul>
          </div>
        </div>
      </div><!-- .row -->

      <div class="row">
        <div class="col-12">
          <div class="date-and-data-info">
            <ul>
              <li><span class="label">Data Sponsor:</span> <span class="netid-large"><%= @presenter.data_sponsor&.uid %></span></li>
              <li><span class="label">Data Manager:</span> <span class="netid-large"><%= @presenter.data_manager&.uid %></span></li>
            </ul>
          </div>
        </div><!-- .col-12 -->
      </div><!-- .row -->
    </div><!-- .col -->

    <div class="col-lg-6">
      <div class="row mt-4">
        <div class="storage-quota container-fluid px-3 py-2 border border-secondary me-0">
          <div class="row mt-2 mb-4">
            <div class="col-6">
              <b>Storage</b> <span class="storage-quota-total text-secondary">(<%= @presenter.formatted_storage_capacity(session_id: current_user.mediaflux_session) %> GB)</span>
            </div>
            <div class="col-6 text-end">
              <%= link_to "Request More", "https://tigerdata.princeton.edu/form/quota-increase-request", target: "_blank" %>
            </div>
          </div>
          <div class="row my-2">
            <div class="progress" role="progressbar" aria-label="Storage quota usage" aria-valuenow="<%= @presenter.formatted_quota_percentage(session_id: current_user.mediaflux_session) %>" aria-valuemin="0" aria-valuemax="100">
              <div class="progress-bar" style="width: <%= @presenter.quota_percentage(session_id: current_user.mediaflux_session) %>%"></div>
            </div>
          </div>
          <div class="row my-2">
            <%= @presenter.quota_usage(session_id: current_user.mediaflux_session) %>
          </div>
        </div>
      </div><!-- .row -->
    </div><!-- .col -->
  </div><!-- .row -->
</div><!-- #project-details-heading -->

<script type="module">

// https://rubyyagi.com/how-to-truncate-long-text-and-show-read-more-less-button/
var $element = $('#description-text')[0];
      if ($element !== undefined) {
        var textTruncated = ($element.offsetHeight < $element.scrollHeight || $element.offsetWidth < $element.scrollWidth)
        if (!textTruncated) {
          $('#show-more-less-link').addClass("invisible");
        }
      }
      const ExcerptWidget = {
        showMore: function(showMoreLinksTarget, excerptTarget) {
         const showMoreLinks = document.querySelectorAll(showMoreLinksTarget);

          showMoreLinks.forEach(function(link) {
             const excerpt = document.querySelector(excerptTarget);
             showMoreLess.showMore(link, excerpt);
           });
          }
         };
         ExcerptWidget.showMore('.show-more', '#description-text');
</script>

app/views/projects/details.html.erb
<%= render partial: "project_details_heading" %>

<show id="show">

<div id="project-nav">
  <button id="project-content" class="tab-nav"> Content Preview </button>
  <button id="project-details" class="tab-nav"> Details </button>
</div>

<ul class="details basic-details-fields">
  <div class="detail-heading">
      <div class="heading-text" id="basic-details-section">Basic Details
    <% # Removing edit until SpaceGhost https://github.com/pulibrary/tigerdata-app/issues/1509 %>
    <% # link_to "Edit", edit_project_path(@project.id), id:"revisible-heading", class: "btn btn-primary btn-sm" %>
  </div>
  </div>
  
  <div class="detail-pair">
    <li class="detail-subheading">Project Title</li>
    <p class="detail-value"><%= @presenter.title %></p>
  </div>

  <div class="detail-pair">
    <li class="detail-subheading">Project ID</li>
    <p class="detail-value"><%= @presenter.project_id %></p>
  </div>

  <div class="detail-pair">
    <li class="detail-subheading">Project Directory</li>
    <p class="detail-value"><%= @presenter.project_directory %></p>
  </div>

  <div class="detail-pair">
    <li class="detail-subheading">Project Purpose</li>
    <p class="detail-value"><%= @presenter.project_purpose %></p>
  </div>

  <div class="detail-pair">
    <li class="detail-subheading">Department(s)</li>
    <p class="detail-value">
      <% if @presenter.departments.empty? %>
        <strong class="px-0">&mdash;</strong>
      <% else %>
        <%= @presenter.departments.join(", ") %>
      <% end %>
    </p>
  </div>


</ul>

<ul class="details basic-details-fields">
  <div class="detail-heading">
      <div class="heading-text" id="roles-and-people-section">Roles and People
    <% # Removing edit until SpaceGhost https://github.com/pulibrary/tigerdata-app/issues/1509 %>
    <% # link_to "Edit", edit_project_path(@project.id), id:"revisible-heading", class: "btn btn-primary btn-sm" %>
  </div>
  </div>

  <div class="detail-pair">
    <li class="detail-subheading">Data Sponsor</li>
    <p class="detail-value"><%= @presenter.data_sponsor.display_name_safe %></p>
  </div>

  <div class="detail-pair">
    <li class="detail-subheading">Data Manager</li>
    <p class="detail-value"><%= @presenter.data_sponsor.display_name_safe %></p>
  </div>

  <div class="detail-pair">
    <li class="detail-subheading">Data User(s)</li>
    <p class="detail-value">
      <% if @presenter.data_user_names == 0 %>
        <strong class="px-0">&mdash;</strong>
      <% else %>
        <%= @presenter.data_user_names %>
      <% end %>
    </p>
  </div>
</ul>

<ul class="details basic-details-fields">
  <div class="detail-heading">
    <div class="heading-text" id="storange-and-access-section">Storage and Access</div>
  </div>

  <ul class="sub-details basic-details-fields">
    <div class="detail-sub-heading">
      <div class="heading-text">Storage Capacity</div>
    </div>

    <div class="detail-pair">
    <li class="detail-subheading">Requested</li>
    <p class="detail-value"><%= "#{@requested_size} #{@requested_unit}" %></p>
    </div>

    <div class="detail-pair">
    <li class="detail-subheading">Approved</li>
    <p class="detail-value"><%= "#{@approved_size} #{@approved_unit}" %></p>
    </div>
  </ul>

  <div class="detail-pair">
    <li class="detail-subheading">Estimated Number of Files</li>
    <p class="detail-value"><%= @presenter.number_of_files %></p>
  </div>



  <ul class="sub-details basic-details-fields">
    <div class="detail-sub-heading">
      <div class="heading-text">Connection Options</div>
    </div>

    <div class="detail-pair">
    <li class="detail-subheading">High Performance Computing</li>
    <p class="detail-value"><%= @presenter.hpc %></p>
    </div>

    <div class="detail-pair">
    <li class="detail-subheading">Network File Share</li>
    <p class="detail-value"><%= @presenter.smb %></p>
    </div>

    <div class="detail-pair">
    <li class="detail-subheading">Globus Transfer Access</li>
    <p class="detail-value"><%= @presenter.globus %></p>
    </div>
  </ul>

   
<% if @project.in_mediaflux? && (current_user.developer? || current_user.eligible_sysadmin?) %>

  <div class="detail-pair">
  <li class="detail-subheading">Mediaflux ID</li>
  <p class="detail-value"><%= @project.mediaflux_id %></p>
  </div>
<% elsif !@project.in_mediaflux? %>
  <li class="detail-subheading">Mediaflux ID</li>
  <p class="detail-value">This project has not been saved to Mediaflux</p>
  </div>
<% end %>
</ul>

<ul class="details basic-details-fields">
  <div class="detail-heading">
    <div class="heading-text" id="provenance-section">Provenance</div>
  </div>

  <ul class="sub-details basic-details-fields">
    <div class="detail-sub-heading">
      <div class="heading-text">Submission</div>
    </div>
    <% @provenance_events.each do |event| %>
      <li class="provenance"> <%= event.event_details %>, <%=event.created_at.to_time.in_time_zone("America/New_York").iso8601%>
      <% if current_user.eligible_sysadmin? && event.event_type = ProvenanceEvent::DEBUG_OUTPUT_TYPE && event.event_note %>
        <blockquote>
          <%= event.event_note %>
        </blockquote>
      <% end %>
    <% end %>
  </ul>
</ul>

<script type="module">
  projectStyle('<%= @project_session %>');
  projectTab("<%= project_path %>", "<%= project_details_path %>");
</script>

app/views/projects/index.html.erb
<h1>Projects</h1>

<h2>Search</h2>
<p> This field searches the title of the projects.  It is case insensitive and you can add wild cards (eg. pop*). </p>
<%= form_with url: projects_path, method: :get do |form| %>
  <%= form.label :query, "Mediaflux Projects whose title matches:" %>
  <%= form.search_field :title_query, value: @title_query, style: "width: 100%" %>
  <%= form.submit "Search" %>
<% end %>
<div>
<br/>
<h2>Results</h2>
  <ul>
  <% @project_presenters.each do |presenter| %>
    <li>
     <div><%= link_to(presenter.title, presenter.project) %></div>
     <div>Mediaflux id: <%= presenter.mediaflux_id %></div>
     <div><%= presenter.project_directory %></div>
    </li>
  <% end %>
  </ul>
</div>

app/views/projects/show.html.erb
<%= render partial: "project_details_heading" %>

<content id= "content">
  <div class="container-fluid">
    <div id="project-nav">
      <button id="project-content" class="tab-nav"> Content Preview </button>
      <button id="project-details" class="tab-nav"> Details </button>
    </div>
    <div class="row align-items-center contents-summary">
      <div class="col-sm-2 file-inventory">File Inventory:</div>
      <div class="col-sm-2 file-total-label">Total Files: <%= ActiveSupport::NumberHelper.number_to_delimited(@num_files) %></div>
      <div class="col-sm-8 text-end divider">
        <div name="project-contents-preview">
          <button class="btn btn-secondary" popovertarget="list-contents-modal">Download Complete List</button>
        </form>
      </div>
    </div>

    <%= render partial: "contents", locals: { files: @files } %>
    <section class="project-alerts my-4">
      <div class="row">
        <div class="col">
          <div id="project-alert" class="alert alert-primary d-none my-1" role="alert" ></div>
        </div>
      </div>
    </section>
  </content>

</div>

<div popover="auto" id="list-contents-modal" class="pul-popover">
  <div class="modal-content">
    <div class="modal-title-frame"> 
      <div class="model-title">List Project Contents</div>
      <input type=button popovertarget="list-contents-modal" popovertargetaction="hide" class="pul-popover-close" data="cancel"></input>
    </div>
    <div class="draft-content">
      <div class="modal-body">
        This will generate a list of <%= @num_files %> files and their attributes in a downloadable CSV. Do you wish to continue?

        <span class="latest-download-link"><%= render partial: "latest_download_link", locals: { project: @project } if @latest_completed_download %></span>
      </div>
      <div class="button-frame">
        <button type="button" id="request-list-contents" class="btn btn-success" data-list-contents-path="<%= project_list_contents_path %>"
                popovertarget="list-contents-modal" popovertargetaction="hide" >Yes</button>
        <button type="button" class="btn btn-danger" popovertarget="list-contents-modal" popovertargetaction="hide">No</button>
      </div>
    </div>
  </div>
</div>
<script type="module">
    projectStyle('<%= @project_session %>');
    projectTab("<%= project_path %>", "<%= project_details_path %>");
    setupTable('#project-contents');
</script>